version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: ./user-service/Dockerfile
    ports:
      - "8082:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/usuario_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - my-network
    depends_on:
      db:
        condition: service_healthy

  task-service:
    build:
      context: ./task-service
      dockerfile: ./task-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tarefa_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - my-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Gerenciamneto-tarefas/gerenciamento-tarefas
      dockerfile: DockerFile
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      user-service:
        condition: service_started
      task-service:
        condition: service_started

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: usuario_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    networks:
      - my-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
    driver: local
