server:
  port: 8085

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/usuarios/**
          filters:
            - RewritePath=/api/(?<s>.*), /${s}
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tarefas/**
          filters:
            - RewritePath=/api/(?<s>.*), /${s}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG