spring:
  application:
    name: api-gateway  # Nome da aplicação (deve ser igual ao nome do arquivo de configuração no Config Server)
  cloud:
    config:
      uri: http://config-server:8888  # URL do Config Server
