server:
  port: 8080

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tarefa_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
    show-sql: true
  datasource.hikari.maximum-pool-size: 10

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
